### ISSUE TITLE
fit_aq_response error

### ISSUE THREAD

**Issue by hoganhaben** [cdmuir/photosynthesis#10]
Hi, 

I am getting an error when i try to fit light curves with the photosynthesis package.  

code I am using to fit light curve:  

fit.A1 <- fit_aq_response(lc_data[lc_data$plant_ID =="A1",], varnames = list(A_net="A", PPFD="Qin"), title = "A1")

The error is: "Error in model.frame.default(formula = A_net ~ Q_abs, data = data[data$Q_abs < : invalid type (list) for variable 'A_net'"
I get the same error for fit_many; 

lc_fits <- fit_many(data = lc_data, 
                    varnames = list(A_net="A", PPFD="Qin", group = "plant_ID"), 
                    funct=fit_aq_response, 
                    group = "plant_ID")

The traceback shows that this is failing when the code goes to pull the coef for phi_J / Rd, for the nls starting parameters.  Here is the traceback stack:

8.  model.frame.default(formula = A_net ~ Q_abs, data = data[data$Q_abs < 
300, ], drop.unused.levels = TRUE)
7.  stats::model.frame(formula = A_net ~ Q_abs, data = data[data$Q_abs < 
300, ], drop.unused.levels = TRUE)
6.  eval(mf, parent.frame())
5.  eval(mf, parent.frame())
4.  lm(A_net ~ Q_abs, data[data$Q_abs < 300, ])
3.  coef(lm(A_net ~ Q_abs, data[data$Q_abs < 300, ]))
2.  nlsLM(data = data, A_net ~ aq_response(k_sat, phi_J, Q_abs = data$Q_abs, 
theta_J) - Rd, start = list(k_sat = max(data$A_net), phi_J = coef(lm(A_net ~ 
Q_abs, data[data$Q_abs < 300, ]))[2], theta_J = 0.85, Rd = -coef(lm(A_net ~ 
Q_abs, data[data$Q_abs < 300, ]))[1]), lower = c(min(data$A_net), ...
1.  fit_aq_response(lc_data[lc_data$plant_ID == "A1", ], varnames = list(A_net = "A", 
PPFD = "Qin"), title = "A1")

Any Ideas?

data are here: [Ardisia_LightCurveData.csv](https://github.com/cdmuir/photosynthesis/files/9911400/Ardisia_LightCurveData.csv)
 
code to read in datafile: library(readr)
lc_data <- read_csv("Ardisia_LightCurveData.csv",
                    col_types = cols(Date = col_date(format = "%Y-%m-%d"),
                                     plant_ID = col_factor(levels = c("A1","C1", "A2", "C2", "A3", "C3","A4", "C4",
                                                                      "A5", "C5", "A6","C6", "A7", "C7", "A8", "C8"))))

thanks, Aaron

**Comment by cdmuir** [comment]
@hoganhaben I'll try to take a look shortly. Thanks for sharing the code and data.

**Comment by cdmuir** [comment]
OK, I think this is caused if `lc_data` is a tibble rather than a data.frame. The following code works for me:

```
library(dplyr)
library(photosynthesis)

lc_data = read.csv("Ardisia_LightCurveData.csv") |>
  filter(plant_ID == "A1") |>
  rename(A_net = A, PPFD = Qin)

fit.A1 <- fit_aq_response(data = lc_data)
```

But I got the same error as you when I used `read_csv()` rather than `read.csv()` because the former reads data in as a tibble rather than data.frame. I'll see if I can fix this so it works with tibbles in the future.

**Comment by hoganhaben** [comment]
Thanks very much, Dr. Muir. 

I got it working.  tibbles ugh!.  I appreciate your time.  Here the fits, revised datafile (there was a minor error with A1 there) and a knitted html.  you may use these if you want for teaching.   best, Aaron 

[Ardisia_LightCurveData.csv](https://github.com/cdmuir/photosynthesis/files/9940115/Ardisia_LightCurveData.csv)

**Comment by hoganhaben** [comment]
got it working.  sharing these, in case you are interested in them.

thank you for your time.
Aaron
