### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by gonzalodqa** [cdmuir/photosynthesis#11]
Hi, 
I am new and I have problems installing the package. 
I am running R studio and when I called the installation of the package it goes through and at the end I get an "installation of package ‘photosynthesis’ had non-zero exit status" message. 
I have tried several times and I cannot seem to be able to install the package 
Is there something I am doing wrong or are some additional packages that I should install first?
Thank you for all your help

**Comment by cdmuir** [comment]
This is a generic R problem that I cannot assess without more information about your environment.
