### ISSUE TITLE
modeling with just a few points

### ISSUE THREAD

**Issue by samanthastutz** [cdmuir/photosynthesis#13]
Are there a minimum number of points required for fitting the light-response curves?  I am trying to fix curves with only 6 points including an irradiance of zero--so I really only have five points for fitting.  I have a few curves that worked well and gave expected fits.  

Thank you,
Sam Stutz

**Comment by cdmuir** [comment]
For nonlinear least squares you need at least one more data point that the number of parameters, so 5 is the absolute minimum. However, to have reliable estimates you would want more than the bare minimum. 6 is pretty low unless you can pool across curves using a multilevel model.

**Comment by CourtneyCampany** [comment]
Is it possible to use the map function in purrr to run multiple co2 response curves? I am struggling with changing the .x and .f inputs from the light response vignette example (sorry not a tidyverse expert).

**Comment by cdmuir** [comment]
I haven't updated `fit_aci_response` to have the same syntax as other fitting functions, but you could still use `purrr::map()` to fit multiple curves. In the example below, you would need to change `dat` to be a data.frame with your data and adjust the variable `group` to be your grouping variable.

```
library(dplyr)
library(photosynthesis)
library(purrr)

# Read in your data
dat = system.file("extdata", "A_Ci_Q_data_1.csv", package = "photosynthesis") |>
  read.csv() |>
  mutate(
    # Set grouping variable
    group = as.factor(round(Qin, digits = 0)),
    # Convert data temperature to K
    T_leaf = Tleaf + 273.15
  ) |>
  rename(A_net = A, PPFD = Qin, C_i = Ci)

fit = dat |>
  split(~ group) |>
  map(fit_aci_response)
```

**Comment by CourtneyCampany** [comment]
Thanks so much!!! It worked great.
Court
