### ISSUE TITLE
error reading licor data using read_licor()

### ISSUE THREAD

**Issue by mollyng** [cdmuir/photosynthesis#15]
hi! getting a read error when trying to read my file! thanks for your help.
df<-read_licor("file_name.xlsx", bluestem_version = "2.0.04")

Multiple files in zip: reading 'xl/worksheets/sheet1.xml'
Error in first_line:last_line : argument of length 0

**Comment by cdmuir** [comment]
The `read_licor()` function only works with the text-based output, not the excel sheet. Try the text output.
