### ISSUE TITLE
Please undo plan(), if you set it

### ISSUE THREAD

**Issue by HenrikBengtsson** [cdmuir/photosynthesis#4]
In order to not override with what future plan the end-users might already have set elsewhere, please undo what you set in

https://github.com/cdmuir/photosynthesis/blob/32e4bf44360874abdfdebcde0a57c24732eb4885/R/photosynthesis.R#L238

See Section 'For package developers' in `?future::plan` for details, but the gist is to use:

```r
oplan <- plan(new_set_of_strategies)
on.exit(plan(oplan), add = TRUE)
```

so that the future plan returns to whatever it was before your function was called.

**Comment by cdmuir** [comment]
Thank you for the suggestion. I have removed `if (parallel) future::plan("multisession")` in the dev branch. I will add a note to the vignette before closing.

**Comment by cdmuir** [comment]
updated vignette
