### ISSUE TITLE
&& instead of &

### ISSUE THREAD

**Issue by HenrikBengtsson** [cdmuir/photosynthesis#5]
While I'm here and since I spotted it.  Instead of using `&` as in:

https://github.com/cdmuir/photosynthesis/blob/32e4bf44360874abdfdebcde0a57c24732eb4885/R/photosynthesis.R#L240

it is safer to explicitly use `&&`, e.g.

```r
if (progress && !parallel) ...
```

`&` is a vector operation whereas `&&` applies only scalars, which you have here.

**Comment by cdmuir** [comment]
Changed as suggested
