### ISSUE TITLE
temp_resp1 and temp_resp2 are not documented correctly

### ISSUE THREAD

**Issue by AleMorales** [cdmuir/photosynthesis#6]
The help of `temp_resp1` and `temp_resp2` claims to implement functions following Bernacchi et al,. (2002, Plant Phys). That is not correct as Bernacchi et al. use a different formulation that introduces an additional parameter called scaling constant and it does not use a reference temperature. I check that if one was to use the parameters values reported by Bernacchi et al. (2002) in temp_resp2 one gets a different curve from the original, given the differences in the functions. A better reference would be Medlyn et al. (2002, PCE) that uses the same temperature functions as in this package.

**Comment by cdmuir** [comment]
Thank you for bringing this to our attention. I actually used equations from Buckley and Diaz-Espejo (2015, PCE) which cited Bernacchi et al,. (2002, Plant Phys). Their equations do not appear identical to Medlyn et al. (2002, PCE) in my testing unless I made an error with the temperature units. Anyway, I know the equations `temp_resp1` and `temp_resp2` match that in Buckley and Diaz-Espejo (2015, PCE), so I changed reference to that paper in v2.0.1 for now.
