### ISSUE TITLE
Graceful failure in fit_many

### ISSUE THREAD

**Issue by ginavong** [cdmuir/photosynthesis#8]
Is there a way to "fail gracefully" in fit_many? So that if one of the fits don't work, it shows an error but will still run the others and give an output?

A bit frustrating (and takes a while to debug) when doing fit_many with a large dataset and it fails because 1 row has an NA or other error.

**Comment by hoganhaben** [comment]
maybe use try()   

e.g.,
try(fit_many(...))

**Comment by cdmuir** [comment]
Sorry Gina (@ginavong), this caught me while I was teaching and I forgot to respond until I saw Aaron's (@hoganhaben) response. I am working on some package updates now, but I am not sure when I'll be able to get to `fit_many()`. Here is a generic way to at least figure out where the problematic data sets are:

```
library(photosynthesis)

data <- read.csv(system.file("extdata", "A_Ci_Q_data_1.csv",
                             package = "photosynthesis"
))

# Define a grouping factor based on light intensity to split the ACi
# curves
data$Q_2 <- as.factor((round(data$Qin, digits = 0)))

# Convert leaf temperature to K
data$T_leaf <- data$Tleaf + 273.15

# Introduce NA
data$T_leaf[32] <- NA

# Fit many curves (causes error)
fits <- fit_many(
  data = data,
  varnames = list(
    A_net = "A",
    T_leaf = "T_leaf",
    C_i = "Ci",
    PPFD = "Qin"
  ),
  funct = fit_aci_response,
  group = "Q_2"
)

# Use purrr to figure out which group is causing error
data |>
  split(~ Q_2) |>
  purrr::imap(function(.x, .y) {
    # print group name
    print(.y)
    try(fit_aci_response(
      data = .x,
      varnames = list(
        A_net = "A",
        T_leaf = "T_leaf",
        C_i = "Ci",
        PPFD = "Qin"
      )
    ))
  })
```
